steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/beta-testnet-20250403/cloud-run-source-deploy/homebrew/homebrew-agents', '.' ]
  env: 'DOCKER_BUILDKIT=1'
images:
  - 'europe-west1-docker.pkg.dev/beta-testnet-20250403/cloud-run-source-deploy/homebrew/homebrew-agents'